server:
  port: 8081
spring:
  application:
    name: BOOKSTORE-API
  jpa:
    database: postgresql

  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver